# this is the Makefile for the kgui samples

.PHONY : all # .PHONY ignores files named all

all:	# generate samples
	$(MAKE) -C audio
	$(MAKE) -C browse
	$(MAKE) -C csvedit
	$(MAKE) -C events
	$(MAKE) -C gamma
	$(MAKE) -C katipo
	$(MAKE) -C mandelbrot
	$(MAKE) -C report
	$(MAKE) -C space

clean:		# clean samples
	$(MAKE) -C audio clean
	$(MAKE) -C browse clean
	$(MAKE) -C csvedit clean
	$(MAKE) -C events clean
	$(MAKE) -C gamma clean
	$(MAKE) -C katipo clean
	$(MAKE) -C mandelbrot clean
	$(MAKE) -C report clean
	$(MAKE) -C space clean
